export const TaskStatus = Object.freeze({
  PENDING: 'PENDING',
  RUNNING: 'RUNNING',
  COMPLETED: 'COMPLETED',
  DEAD: 'DEAD'
});

export const TaskType = Object.freeze({
  PURCHASE_CARD: 'PURCHASE_CARD',
  SUBMIT_RECHARGE: 'SUBMIT_RECHARGE',
  POLL_RECHARGE: 'POLL_RECHARGE',
  SYNC_CARD_TRANSACTIONS: 'SYNC_CARD_TRANSACTIONS',
  RECHECK_CANCELLATION: 'RECHECK_CANCELLATION'
});
