export const TaskStatus = Object.freeze({
  PENDING: 'PENDING',
  RUNNING: 'RUNNING',
  COMPLETED: 'COMPLETED',
  DEAD: 'DEAD'
});

export const TaskType = Object.freeze({
  ASSIGN_CARD: 'ASSIGN_CARD',
  BROWSER_PREFLIGHT: 'BROWSER_PREFLIGHT',
  PREPARE_RECHARGE: 'PREPARE_RECHARGE',
  SUBMIT_RECHARGE: 'SUBMIT_RECHARGE',
  POLL_RECHARGE: 'POLL_RECHARGE',
  SYNC_CARD_TRANSACTIONS: 'SYNC_CARD_TRANSACTIONS',
  RECHECK_CANCELLATION: 'RECHECK_CANCELLATION',
  // D-411 按单补钱：发一次补钱请求 / 查到账
  TOP_UP_CARD: 'TOP_UP_CARD',
  CHECK_TOP_UP: 'CHECK_TOP_UP'
});
