import assert from 'node:assert/strict';
import {allowedTaskTypesFor} from '../../v1/src/workers/worker-runtime.js';
import {reconcileByRoute} from '../../v1/src/domain/route-reconciliation.js';
import {createCdkDeliveryService} from '../../v1/src/services/cdk-delivery-service.js';
import {BrowserCardTransactionReader} from '../../browser-mvp/src/browser-card-transaction-reader.js';
const results=[];
const settings={dispatchNewRecharges:true,browserDispatchEnabled:true};
const off=allowedTaskTypesFor(settings,{providerReadsEnabled:false});
const on=allowedTaskTypesFor(settings,{providerReadsEnabled:true});
assert(!off.includes('SUBMIT_RECHARGE')&&on.includes('SUBMIT_RECHARGE'));
results.push({id:'G01',reproduced:true,withoutProviderReads:off,withProviderReads:on});
const base={executorKind:'BROWSER',orderStatus:'RECHARGE_SUCCESS',createAttempted:true,hasRechargeSuccessEvent:true,actualPaymentAmount:'16',actualPaymentCurrency:'USD',transactionEvidenceSynced:true,successfulPurchaseExists:true,paymentMatched:false,paymentSettled:true};
const missing=reconcileByRoute({...base,rechargeOrderNo:null});
const present=reconcileByRoute({...base,rechargeOrderNo:'fixture-reference'});
assert(!missing.issue&&present.issue);
results.push({id:'G03',reproduced:true,missingReference:missing,presentReference:present});
let inserts=0; const id='11111111-1111-4111-8111-111111111111';
const conn={async beginTransaction(){},async commit(){},async rollback(){},release(){},async query(sql){if(sql.includes('SELECT id, batch_no, status'))return [[{id,batch_no:'fixture-batch',status:'AVAILABLE'}]];if(sql.includes('INSERT INTO cdk_delivery_events')){inserts++;return [{affectedRows:1}]};throw Error('Unexpected SQL');}};
const svc=createCdkDeliveryService({pool:{async getConnection(){return conn;}},recipientReferenceHmacKey:Buffer.alloc(32,7)});
const input={cdkId:id,eventType:'DELIVERED',recipientReference:'fixture-recipient',channel:'manual'};
const first=await svc.recordDelivery(input);const second=await svc.recordDelivery(input);
assert.equal(inserts,2);assert.notEqual(first.eventIds[0],second.eventIds[0]);
results.push({id:'A07',reproduced:true,identicalRequestInsertCount:inserts,note:'Actual service with fake database; proves no service-level replay suppression, not real duplicate delivery.'});
assert.throws(()=>new BrowserCardTransactionReader({sourceKind:'HNSKJ',provider:{transactions(){}},providerCardId:'fixture',runId:'fixture',submitIntentAt:null}),/submitIntentAt/);
results.push({id:'A11',reproduced:true,note:'Reader rejects absent intent; full LIVE timing integration still pending.'});
console.log(JSON.stringify({mode:'OFFLINE_NO_CUSTOMER_NO_PAYMENT',results},null,2));
