CREATE TABLE IF NOT EXISTS card_catalog_snapshots (
  provider VARCHAR(32) PRIMARY KEY,
  payload_json JSON NOT NULL,
  synced_at TIMESTAMP(3) NOT NULL,
  updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
